<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-QMO9A9N" name="uitest.Demo1" tests="44" failures="1" timestamp="3 Dec 2019 02:37:28 GMT" time="576.650" errors="0">
  <testcase name="setquit" time="13.453" classname="uitest.Demo1"/>
  <testcase name="setpassowrd" time="12.659" classname="uitest.Demo1"/>
  <testcase name="freight" time="11.175" classname="uitest.Demo1"/>
  <testcase name="db" time="9.386" classname="uitest.Demo1"/>
  <testcase name="setpassowrd" time="12.642" classname="uitest.Demo1"/>
  <testcase name="freight" time="11.688" classname="uitest.Demo1"/>
  <testcase name="addarticle" time="21.690" classname="uitest.Demo1"/>
  <testcase name="addarticle" time="21.154" classname="uitest.Demo1"/>
  <testcase name="addarticle" time="20.975" classname="uitest.Demo1"/>
  <testcase name="freight" time="3.833" classname="uitest.Demo1"/>
  <testcase name="setpassowrd" time="12.518" classname="uitest.Demo1"/>
  <testcase name="addarticle" time="20.871" classname="uitest.Demo1"/>
  <testcase name="setpassowrd" time="12.597" classname="uitest.Demo1"/>
  <testcase name="freight" time="11.469" classname="uitest.Demo1"/>
  <testcase name="takeself" time="3.787" classname="uitest.Demo1"/>
  <testcase name="setpassowrd" time="12.621" classname="uitest.Demo1"/>
  <testcase name="setpassowrd" time="12.600" classname="uitest.Demo1"/>
  <testcase name="freight" time="11.961" classname="uitest.Demo1"/>
  <testcase name="addarticle" time="22.025" classname="uitest.Demo1"/>
  <testcase name="takeself" time="12.287" classname="uitest.Demo1"/>
  <testcase name="addarticle" time="21.114" classname="uitest.Demo1"/>
  <testcase name="takeself" time="3.932" classname="uitest.Demo1"/>
  <testcase name="addarticle" time="21.196" classname="uitest.Demo1"/>
  <testcase name="delivery" time="14.802" classname="uitest.Demo1"/>
  <testcase name="takeself" time="14.011" classname="uitest.Demo1"/>
  <testcase name="addarticle" time="21.188" classname="uitest.Demo1"/>
  <testcase name="setnav" time="16.523" classname="uitest.Demo1"/>
  <testcase name="takeself" time="3.912" classname="uitest.Demo1"/>
  <testcase name="login" time="17.887" classname="uitest.Demo1"/>
  <testcase name="netset" time="2.518" classname="uitest.Demo1"/>
  <testcase name="delivery" time="18.588" classname="uitest.Demo1"/>
  <testcase name="xitong" time="1.176" classname="uitest.Demo1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at uitest.Demo1.xitong(Demo1.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- xitong -->
  <testcase name="freight" time="11.236" classname="uitest.Demo1"/>
  <testcase name="addarticle" time="24.558" classname="uitest.Demo1"/>
  <testcase name="takeself" time="3.895" classname="uitest.Demo1"/>
  <testcase name="addarticle" time="23.070" classname="uitest.Demo1"/>
  <testcase name="freight" time="14.354" classname="uitest.Demo1"/>
  <testcase name="delivery" time="15.336" classname="uitest.Demo1"/>
  <testcase name="takeself" time="13.174" classname="uitest.Demo1"/>
  <testcase name="setshop" time="5.550" classname="uitest.Demo1"/>
  <testcase name="takeself" time="11.923" classname="uitest.Demo1"/>
  <testcase name="takeself" time="3.889" classname="uitest.Demo1"/>
  <testcase name="setpassowrd" time="12.657" classname="uitest.Demo1"/>
  <testcase name="setback" time="8.770" classname="uitest.Demo1"/>
</testsuite> <!-- uitest.Demo1 -->
